///** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// module.exports = {
  //tutorialSidebar: [
    {
      // type: 'autogenerated',
      // dirName: '.', // 👈 scan the whole "docs" folder
    }
    module.exports = {
  projectsidebar: [
    {
      type: 'category',
      label: 'About Refract',
      items: [
        'introduction',
        {
          type: 'category',
          label: 'Concepts',
          items: [
            'concepts/lens',
            'concepts/optics',
            'concepts/refractions'
          ],
        },
      ],
    },
  ],

  tutorialSidebar: [
    {
      type: 'category',
      label: 'Refract Usage Guide',
      items: [
        'getting-started',
         {
          type: 'category',
          label: 'Describing UI',
          items:[ {type: 'autogenerated', dirName: 'describing -ui',},]
         
        },
        {
          type: 'category',
          label: 'Managing State',
          items:[ {type: 'autogenerated', dirName: 'managing-state',},]
         
        },
       {type:'category',
        label: 'Reusing Logic',
        items : [{type: 'autogenerated', dirName: 'reusing-logic',},]
       },
        
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [{type: 'autogenerated', dirName: 'api',},],
    },
    {
      type: 'doc',
      label: 'Contribute',
      id: 'contributing',
    },
  ],
};